#!/bin/bash

box() {
	TOP_LEFT="\033(0l\033(B"
	TOP_RIGHT="\033(0k\033(B"
	BOTTOM_LEFT="\033(0m\033(B"
	BOTTOM_RIGHT="\033(0j\033(B"
	VERT_LINE="\033(0x\033(B"
	HORIZ_LINE="\033(0q\033(B"

	max_width=0

	# Find the longest line
	for (( i=0; i < ${#box_lines[@]}; i=i+1 )); do
		width=${#box_lines[i]}
		if [ $width -gt $max_width ]; then
			max_width=$width
		fi
	done

	printn() {
		for (( i=0; i < $1; i=i+1 )); do
			echo -en "$2"
		done
	}

	box_width=$((max_width + 2))

	[ -z "$COLUMNS" ] || prefix="$(printn $(((COLUMNS - box_width - 2) / 2)) " ")"

	echo -e "$prefix$TOP_LEFT$(printn $box_width "$HORIZ_LINE")$TOP_RIGHT"

	for (( i=0; i < ${#box_lines[@]}; i=i+1 )); do
		width=${#box_lines[i]}
		space_around=$(((box_width - width) / 2))

		echo -en "$prefix$VERT_LINE$(printn $space_around " ")"
		echo -en ${box_lines[i]}
		echo -n "$(printn $space_around " ")"

		if [ $(((space_around * 2) + $width)) -lt $box_width ]; then
			echo -n " "
		fi

		echo -e "$VERT_LINE"
	done

	echo -e "$prefix$BOTTOM_LEFT$(printn $box_width "$HORIZ_LINE")$BOTTOM_RIGHT"
}
