#!/bin/bash

link() {
    rm -f ~/$1
    if grep -q Microsoft /proc/version; then
        cp -r $(pwd)/$1 ~/$1
    else
	    ln -s $(pwd)/$1 ~/$1
    fi
}

link .vimrc
link .vim
link .bashrc
link .screenrc
link .profile

vim +PluginInstall +qall
