#!/bin/bash

link() {
    if grep -q Microsoft /proc/version; then
        rm -f ~/$1
        cp -r $(pwd)/$1 ~/$1
    else
	    rm -f ~/$1
	    ln -s $(pwd)/$1 ~/$1
    fi
}

link .vimrc
link .vim
link .bashrc

vim +PluginInstall +qall
