#!/bin/bash

link() {
    rm -rf ~/$1
    ln -s $(pwd)/$1 ~/$1
}

mkdir -p ~/bin

link .vimrc
link .vim
link .bashrc
link .tmux.conf
link .profile
link .tmux
rm -f ~/bin/myip
rm -f bin/sess-pick
rm -f bin/ssh-pick
link bin/gssh

vim +PluginInstall +qall

echo "Don't forget to run prefix + I in tmux"
