#!/bin/bash

######################################
# Utilities                          #
######################################

path_add() {
	if ! echo $PATH | grep -E "(^|:)$1(:|$)" >/dev/null && [ -d "$1" ]; then
		export PATH="$1:$PATH"
	fi
}

download() {
	if command -v curl >/dev/null; then
		curl -L $1 >$2
	elif command -v wget >/dev/null; then
		wget -O $2 $1
	else
		pkg_install curl || pkg_install wget || {
			echo "Please install wget or curl"
			exit 1
		}

		download $1 $2
	fi
}

has_cmd() {
	command -v $1 >/dev/null
}

display_step() {
    echo -e "\033[0;36m>> $1\033[0;0m"
}

link() {
	if [ ! -L "$2" ] && [ -e "$2" ]; then
		echo "Making backup for $2"
		mv "$2" "$2.bak"
	fi

	mkdir -p "$(dirname "$2")"
	ln -sf "$1" "$2"
}

######################################
# Platform detection                 #
######################################

PLATFORM_MAC=false
PLATFORM_OPENWRT=false
PLATFORM_PKG=Unknown

[ "$(uname)" == "Darwin" ] && PLATFORM_MAC=true
has_cmd apt-get && PLATFORM_PKG=apt
has_cmd yum && PLATFORM_PKG=yum
has_cmd apk && PLATFORM_PKG=apk
$PLATFORM_MAC && PLATFORM_PKG=brew

if ! $PLATFORM_MAC; then
	fgrep OpenWrt /proc/version && PLATFORM_OPENWRT=true
fi

export PLATFORM_MAC PLATFORM_PKG PLATFORM_OPENWRT

print_platform() {
	echo "PLATFORM_PKG = $PLATFORM_PKG"
	echo "PLATFORM_MAC = $PLATFORM_MAC"
	echo "PLATFORM_OPENWRT = $PLATFORM_OPENWRT"
}

######################################
# Package management                 #
######################################

as_root() {
	if has_cmd sudo; then
		sudo $*
	else
		$*
	fi
}

_pkg_lists_updated=false
pkg_update_lists() {
	$_pkg_lists_updated && return

	case "$PLATFORM_PKG" in
		apt) as_root apt-get update -y ;;
		yum) ;;
		apk) as_root apk update ;;
		brew) ;;
		*)
			echo "We could not identify your package manager"
			exit 127
			;;
	esac

	_pkg_lists_updated=true
}

_pkg_map() {
	local name="$1"

	# Mappings to platform specific package names
	case "$PLATFORM_PKG-$1" in

	esac

	echo $name
}

pkg_install() {
	pkg_update_lists

	local list=""
	while [[ $# -gt 0 ]]; do
		list="$list $(_pkg_map $1)"
		shift
	done

	case "$PLATFORM_PKG" in
		apt) as_root apt-get install -y $list ;;
		yum) as_root yum install $list ;;
		apk) as_root apk add $list ;;
		brew) brew install $list ;;
		*)
			echo "We could not identify your package manager"
			exit 127
			;;
	esac
}

######################################
# Environment setup                  #
######################################

path_add ~/bin
path_add ~/dotfiles/bin

