#!/bin/bash
. ~/dotfiles/platform

rootfs="$(df -H / | tail -1 | awk '{print $3 "/" $2}')"
command -v docker >/dev/null && containers="$(docker ps -q 2>/dev/null | wcl)"

if [ "$containers" == "0" ] || [ -z "$containers" ]; then
	containers=
else
	containers="$containers ctr | "
fi 

echo "$users$rootfs"
