#!/bin/bash

# Print the progress and heading
PROGRESS=0
PROGRESS_TOTAL=8
progress() {
    PROGRESS=$(($PROGRESS + 1))
    echo "[$PROGRESS/$PROGRESS_TOTAL] $1"
}

# Determine which package manager this system uses
package_manager() {
    for manager in "apt-get"; do
        which $manager >/dev/null
        if [ $? -eq 0 ]; then
            echo $manager
            return
        fi
    done
}

# Show the install message
install_msg() {
    echo "The following programs are required $DEPS_NEEDED"
    
    if [ "$1" == "-r" ]; then
        echo "Either install them manually and run ~/dotfiles/update or run ~/dotfiles/update as root"
    else
        echo "Install them manually and run ~/dotfiles/update"
    fi

    exit 1
}

# Print a command and then run it
print_run() {
    echo -e ">> $1"
    eval "$1 >/dev/null"
}

# Check for our dependencies
DEPS_NEEDED=
progress "Checking for and installing dependencies"

for dep in "vim" "tmux" "find" "curl" "git"; do
    which $dep >/dev/null
    if [ $? -eq 1 ]; then
        if [ -z "$DEPS_NEEDED" ]; then
            DEPS_NEEDED="$dep"
        else
            DEPS_NEEDED="$DEPS_NEEDED, $dep"
        fi
    fi
done

# Install deps if root or tell the user if to do it
if [ ! -z "$DEPS_NEEDED" ]; then
    if [ $EUID -eq 0 ]; then
        case "$(package_manager)" in
            apt-get)
                apt-get update
                apt-get install -y $(echo $DEPS_NEEDED | sed 's/,//')
                ;;

            *)
                install_msg
                ;;
        esac
    else
        install_msg -r
    fi
fi

# Run the rest of the commands as the original user
if [ $SUDO_USER ] && [ $EUID -eq 0 ]; then
    echo ">> su $SUDO_USER -c ~/dotfiles/update"
    su $SUDO_USER -c ~/dotfiles/update
    exit
fi

# Update repo and submodules
progress "Pulling"
cd ~/dotfiles
print_run "git checkout master"
print_run "git pull"

progress "Updating submodules"
print_run "git submodule init"
print_run "git submodule update"

# Remove old symlinks
progress "Removing old links"
cd ~
for link in $(find . -type l -not -path './dotfiles/*'); do
    if [ ! -z "$(readlink $link | fgrep dotfiles)" ]; then
        rm -rf $link
    fi
done

# Install new links
cd ~/dotfiles
progress "Installing symlinks"

for file in $(ls -1a | tail -n $(($(ls -1a | wc -l) - 2)) | fgrep -v .git | fgrep -v bin | fgrep -v README.md); do
    if [ -f ~/$file ]; then
        print_run "mv ~/$file ~/$file.bak"
    fi

    print_run "ln -s ~/dotfiles/$file ~/$file"
done

mkdir -p ~/bin

for file in $(ls -1 bin); do
    if [ -f ~/bin/$file ]; then
        echo "Moving existing bin/$file to bin/$file.bak"
        mv ~/bin/$file ~/bin/$file.bak
    fi

    ln -s ~/dotfiles/bin/$file ~/bin/$file
done

# Install app plugins
progress "Installing tmux plugins"

print_run 'tmux new-session -s "Dot" -n "Update" ~/.tmux/plugins/tpm/scripts/install_plugins.sh'

progress "Installing vim plugins"

echo ">> vim +PluginInstall +qall"
vim +PluginInstall +qall 2>&1 >/dev/null

progress "Configuring git"

print_run 'git config --global user.name "Ryan Ray"'
print_run 'git config --global user.email "ryan314r@gmail.com"'