#!/bin/bash

. ~/dotfiles/platform

can_install() {
	exit
}

install() {
	# Install vim plug
	mkdir -p ~/.vim/autoload
	download https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim \
		~/.vim/autoload/plug.vim 

	# Link vim dotfiles
	rm -f ~/.vimrc
	ln -s ~/dotfiles/vimrc ~/.vimrc 

	# Install vim via package manager
	if ! has_cmd vim && pkg_version vim | grep -P "(^|:)8\." >/dev/null; then
		pkg_install vim
	fi

	if ! has_cmd vim; then
		ensure_build_tools
	fi

	vim +PlugInstall +qall
}

update() {
	if [ -f ~/bin/vim ]; then
		echo
	fi

	vim +PlugUpgrade +PlugClean +PlugUpdate +qall
}

installer_main $1
