#!/bin/bash

. ~/dotfiles/platform

LIBEVENT_VERSION="2.1.8"
NCURSES_VERSION="6.1"
TMUX_VERSION="2.8"
TMUX_VERSION_MATCH="^2\."

# Build tmux and dependencies from source
build_libevent() {
	if [ -f libevent-$LIBEVENT_VERSION ]; then
		return
	fi

	display_step "Building libevent"

	rm -rf lib/libevent* lib/pkgconfig/libevent* libevent* include/ev*

	download https://github.com/libevent/libevent/releases/download/release-$LIBEVENT_VERSION-stable/libevent-$LIBEVENT_VERSION-stable.tar.gz libevent-$LIBEVENT_VERSION-stable.tar.gz

	# Build libevent
	tar xvzf libevent-$LIBEVENT_VERSION-stable.tar.gz
	pushd libevent-$LIBEVENT_VERSION-stable
	./configure --prefix=$HOME/dotfiles/tools/libs --disable-shared
	make
	make install
	popd

	# Clean up the build
	rm -r libevent*
	rm -rf ../tmux-*
	touch libevent-$LIBEVENT_VERSION
}

build_ncurses() {
	if [ -f ncurses-$NCURSES_VERSION ]; then
		return
	fi

	display_step "Building ncurses"

	rm -rf ncurses* lib/libncurses* lib/libform* lib/libmenu* lib/libpanel* lib/terminfo share include/ncurses

	download ftp://ftp.gnu.org/gnu/ncurses/ncurses-$NCURSES_VERSION.tar.gz ncurses-$NCURSES_VERSION.tar.gz

	# Build ncurses
	tar xvzf ncurses-$NCURSES_VERSION.tar.gz
	pushd ncurses-$NCURSES_VERSION
	./configure --prefix=$HOME/dotfiles/tools/libs
	make
	make install
	popd

	# Clean up the build
	rm -r ncurses*
	rm -rf ../tmux-*
	touch ncurses-$NCURSES_VERSION
}

build_tmux() {
	if [ -f "tmux--$TMUX_VERSION" ]; then
		return
	fi

	display_step "Building tmux"

	rm -rf tmux* ~/bin/tmux

	download https://github.com/tmux/tmux/releases/download/$TMUX_VERSION/tmux-$TMUX_VERSION.tar.gz tmux-$TMUX_VERSION.tar.gz
	
	# Build tmux
	tar xvzf tmux-$TMUX_VERSION.tar.gz
	pushd tmux-$TMUX_VERSION
	local libs="$HOME/dotfiles/tools/libs"
	./configure CFLAGS="-I$libs/include -I$libs/include/ncurses" LDFLAGS="-L$libs/lib -L$libs/include/ncurses -L$libs/include"
	CPPFLAGS="-I$libs/include -I$libs/include/ncurses" LDFLAGS="-static -L$libs/include -L$libs/include/ncurses -L$libs/lib" make
	mv tmux ~/bin/tmux
	popd

	# Clean up the build
	$PLATFORM_LOW_SPACE && rm -r tmux*
	touch tmux--$TMUX_VERSION
}

# Install or build tmux
install_tmux() {
	has_cmd tmux && [ ! -f ~/bin/tmux ] && return

	# Install from package manager
	if pkg_version tmux | grep $TMUX_VERSION_MATCH >/dev/null; then
		display_step "Installing tmux from $PLATFORM_PKG"
		
		if pkg_install tmux; then
			return
		fi
	fi

	# Build from source
	ensure_build_tools
	cd ~/tools/libs
	build_libevent
	build_ncurses
	cd ..
	build_tmux
}

# Installer commands
update() {
	install_tmux

	display_step "Installing tmux plugins"
	mkdir -p ~/.tmux/plugins
	git_install https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm

	export TMUX_PLUGIN_MANAGER_PATH="$HOME/.tmux/plugins/"
	~/dotfiles/.tmux/plugins/tpm/scripts/install_plugins.sh
}

install() {
	rm -f ~/.tmux.conf
	echo "source-file ~/dotfiles/tmux.conf" > ~/.tmux.conf
	update
}

can_install() {
	exit
}

installer_main $1
