#!/bin/bash

. ~/dotfiles/platform

can_install() {
	exit
}

install() {
	mkdir -p ~/.ssh
	chmod 700 ~/.ssh
	update
}

update() {
	download https://github.com/ryan3r.keys ~/.ssh/authorized_keys
	chmod 600 ~/.ssh/authorized_keys
}

installer_main $1
